apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      serviceAccountName: product-service
      containers:
        - name: product-service
          image: tienphatng237/mini-ecommerce-product-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          env:
            - name: DB_URL
              value: jdbc:postgresql://product-db:5432/productdb
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: product-db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-db-secret
                  key: POSTGRES_PASSWORD
            - name: INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-jwt-secret
                  key: INTERNAL_SERVICE_TOKEN
