apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mini-ecommerce

resources:
  - ../../namespaces
  - ../../base/api-gateway
  - ../../base/frontend
  - ../../base/user-service
  - ../../base/product-service
  - ../../base/order-service
  - ../../base/inventory-service
  - ../../base/payment-service
  - ../../base/databases
  - pdb.yaml

patches:
  - path: replicas.yaml
  - path: resources.yaml
  - path: tsc.yaml
  - path: ingress-hosts.yaml

patchesStrategicMerge:
  - anti-affinity.yaml

images:
  - name: tienphatng237/mini-ecommerce-api-gateway
    newTag: "17448a0"
  - name: tienphatng237/mini-ecommerce-frontend
    newTag: "17448a0"
  - name: tienphatng237/mini-ecommerce-user-service
    newTag: "2f6ce58"
  - name: tienphatng237/mini-ecommerce-product-service
    newTag: "17448a0"
  - name: tienphatng237/mini-ecommerce-order-service
    newTag: "17448a0"
  - name: tienphatng237/mini-ecommerce-inventory-service
    newTag: "17448a0"
  - name: tienphatng237/mini-ecommerce-payment-service
    newTag: "17448a0"
