apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mini-ecommerce
# =========================
# BASE RESOURCES
# =========================
resources:
  # Namespace
  - ../../namespaces
  # Dev-only Sealed Secrets
  - secrets
  # Core services
  - ../../base/api-gateway
  - ../../base/frontend
  - ../../base/user-service
  - ../../base/product-service
  - ../../base/order-service
  - ../../base/inventory-service
  - ../../base/payment-service
  # Databases (StatefulSet)
  - ../../base/databases
  # Extra dev-only resources
  - pdb.yaml
# =========================
# PATCHES (DEV ONLY)
# =========================
patches:
  # Scale cho dev
  - path: replicas.yaml
  # CPU / Memory limit cho dev
  - path: resources.yaml
  # topologySpreadConstraints
  - path: tsc.yaml
  - path: ingress-hosts.yaml
patchesStrategicMerge:
  - anti-affinity.yaml
# =========================
# IMAGES (DEV TAG)
# =========================
images:
  - name: tienphatng237/mini-ecommerce-api-gateway
    newTag: "17448a0"
  - name: tienphatng237/mini-ecommerce-frontend
    newTag: "17448a0"
  - name: tienphatng237/mini-ecommerce-user-service
    newTag: "2f6ce58"
  - name: tienphatng237/mini-ecommerce-product-service
    newTag: "17448a0"
  - name: tienphatng237/mini-ecommerce-order-service
    newTag: "17448a0"
  - name: tienphatng237/mini-ecommerce-inventory-service
    newTag: "17448a0"
  - name: tienphatng237/mini-ecommerce-payment-service
    newTag: "17448a0"
