apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          resources:
            requests:
              cpu: 50m
              memory: 384Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  template:
    spec:
      containers:
        - name: user-service
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  template:
    spec:
      containers:
        - name: product-service
          resources:
            requests:
              cpu: 50m
              memory: 384Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  template:
    spec:
      containers:
        - name: order-service
          resources:
            requests:
              cpu: 50m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  template:
    spec:
      containers:
        - name: inventory-service
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  template:
    spec:
      containers:
        - name: payment-service
          resources:
            requests:
              cpu: 50m
              memory: 384Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-db
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-db
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-db
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-db
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payment-db
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
