tempo_version: "2.3.1"
tempo_user: "tempo"
tempo_group: "tempo"
tempo_config_dir: "/etc/tempo"
tempo_data_dir: "/var/lib/tempo"
tempo_install_dir: "/opt/tempo"
tempo_archive_path: "/tmp/tempo.tar.gz"
tempo_http_port: 3200
tempo_grpc_port: 9095
tempo_otlp_grpc_port: 4317
tempo_otlp_http_port: 4318

tempo_kubernetes_service_namespaces:
  - mini-ecommerce
  - argocd
tempo_kubernetes_service_name: "tempo"
tempo_kubernetes_service_port: 4317
tempo_kubernetes_http_target_port: 4318
tempo_kubernetes_query_port: 3200
tempo_otlp_http_compat_proxy_port: 14317
