minio_user: "minio"
minio_group: "minio"
minio_data_dir: "/var/lib/minio"
minio_config_dir: "/etc/minio"
minio_env_file: "/etc/default/minio"

minio_binary_url: "https://dl.min.io/server/minio/release/linux-amd64/minio"
minio_binary_checksum: ""

minio_root_user: "minioadmin"
minio_root_password: "minioadmin123"
minio_bind_address: "0.0.0.0"
minio_api_port: 9000
minio_console_port: 9001
