apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: api-gateway
      containers:
        - name: api-gateway
          image: tienphatng237/mini-ecommerce-api-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SECURITY_JWT_SECRET
              value: ""
              valueFrom:
                secretKeyRef:
                  name: auth-jwt-secret
                  key: JWT_SECRET
            - name: INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-jwt-secret
                  key: INTERNAL_SERVICE_TOKEN
