- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Prometheus
  systemd:
    name: prometheus
    state: restarted

- name: Restart Prometheus kube proxy
  systemd:
    name: prometheus-kube-proxy
    state: restarted

