- name: Install ingress-nginx controller
  become: true
  command: k0s kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
  register: ingress_nginx_apply
  retries: 10
  delay: 15
  until: ingress_nginx_apply.rc == 0
  changed_when: ingress_nginx_apply.stdout is search('created')
  tags:
    - ingress

- name: Read ingress-nginx controller external traffic policy
  become: true
  command: k0s kubectl -n ingress-nginx get svc ingress-nginx-controller -o jsonpath={.spec.externalTrafficPolicy}
  register: ingress_nginx_external_traffic_policy
  retries: 10
  delay: 15
  until: ingress_nginx_external_traffic_policy.rc == 0
  changed_when: false
  tags:
    - ingress

- name: Read ingress-nginx controller HTTP nodePort
  become: true
  command: k0s kubectl -n ingress-nginx get svc ingress-nginx-controller -o jsonpath={.spec.ports[0].nodePort}
  register: ingress_nginx_http_nodeport
  retries: 10
  delay: 15
  until: ingress_nginx_http_nodeport.rc == 0
  changed_when: false
  tags:
    - ingress

- name: Pin ingress-nginx controller HTTP nodePort to 30293
  become: true
  command:
    argv:
      - k0s
      - kubectl
      - -n
      - ingress-nginx
      - patch
      - svc
      - ingress-nginx-controller
      - --type
      - merge
      - -p
      - '{"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":"http","nodePort":30293}]}}'
  when: ingress_nginx_http_nodeport.stdout != '30293'
  register: ingress_nginx_http_nodeport_patch
  changed_when: ingress_nginx_http_nodeport_patch.rc == 0
  tags:
    - ingress

- name: Set ingress-nginx controller external traffic policy to Cluster
  become: true
  command:
    argv:
      - k0s
      - kubectl
      - -n
      - ingress-nginx
      - patch
      - svc
      - ingress-nginx-controller
      - --type
      - merge
      - -p
      - '{"spec":{"externalTrafficPolicy":"Cluster"}}'
  when: ingress_nginx_external_traffic_policy.stdout != 'Cluster'
  register: ingress_nginx_external_traffic_policy_patch
  changed_when: ingress_nginx_external_traffic_policy_patch.rc == 0
  tags:
    - ingress

- name: Wait for ingress-nginx controller pod ready
  become: true
  command: k0s kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=180s
  register: ingress_nginx_wait
  retries: 10
  delay: 15
  until: ingress_nginx_wait.rc == 0
  changed_when: false
  tags:
    - ingress
