apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      serviceAccountName: inventory-service
      containers:
        - name: inventory-service
          image: tienphatng237/mini-ecommerce-inventory-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: inventory-db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: POSTGRES_PASSWORD
            - name: PRODUCT_SERVICE_BASE_URL
              value: http://product-service:8080
            - name: INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-jwt-secret
                  key: INTERNAL_SERVICE_TOKEN
            - name: REDIS_ADDR
              value: redis:6379
            - name: ORDER_EVENTS_CHANNEL
              value: orders.events
