---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-jwt-secret
  namespace: mini-ecommerce
spec:
  encryptedData:
    INTERNAL_SERVICE_TOKEN: AgASGdZPjgihxdXXY2C4/Sajt5kroYMwSQXTB1/KR5yAiDKLARJSs+l1yGL1tCb5LeP1iOlqvKQFOFgnGU1t3NmufMvONALeiIBeu3Qb3u0KY0uhLwlz/siFAh0sR9bol7Mg1cSJnA1o2OfpB8KUzMWgOswCFEbidA92x6AQynzcPhg7m44C1HC43K+LdCiYYpvh4LHdxdgRVaO2/1XvT+O4iGHKU6usmWVa0xkotg/6KwRNkD1gfrPsVeA13mCVTuqOloa2s5jpHYiu1G79co0s4ZQZIjxGkU82tpLtJY2ZcsLVrgOhFOZrAx/gJHBKgIjagdeio7M6hgJpIPVvnG/aRTtfkXCtdKpgboPsRydcDQImt9FmmDXMrQwmp5C+yxQMl2HbElIKTO48BKgI6tKDT280JEuP+icvS+v3EKoAlI4TlubFYn17TN8y7zlVo1HImFbdXd2XMMOLDjWFX2xoaMj/bAQtDvjM9fKmdXVM4nI6Pp1NC5ZOJwTe/GVr5xZC6yWaPvLLAW/jNDoMyTt+hsswCLJdVprTqmbr//hRlpnAnUESzA47v3CuEozDb3cabTT/IlYJIuV5RXshfZjy9MWgfx9eHKGsNOvjYrFO6EJ4JiTOOaSbbMoVZgyzIhLTX0CUjncevb6XIFVdhdv6WczgBM2d+CcaUhURG2y63hvcRJGVIj7RFEn0b7PbWR+tXWwhyPMz/Eayw1ErBPs2zNsrE/Gr1P/2BRXwRKYTeUkX8MgUYsbDw08WGQ==
    JWT_SECRET: AgAEgcEx8VlxkUDQOCWcHFD4unZzwxg2qqK+xunjTM/eB4YIuSVBW8GnNRyrvW77t1Altm4PHqo8ukUNcFhoTtc+N/GpXNPhpVzSGdY9Zgtw/7wQu6Ihili+NCzICzBcBt50AXnS7zVFA3LIGLsZzL2XpAsUmInZ5iKBwcVB8MU08RgENYQi6XNuplFY/69420oax/fxgC8pdbv4Ie+U3Xm5y8UnWav/swpD1QPWzA1Pfr0Pkd+fcsw03T5d/FDdt6w4EPxuooZxx07QnbigoJ8o9bAwsGQNKIFrpSgEqqISZPsUF/8iqzQiU7Kf+AZZ3nFoMuMGey8Y0zSkOhf+i7kUckcrxtkkYxTLIJ6MWd7zxElic97UYj1DTL26hBRpe7F2cPSnrQRATO4LO6ubEZhtvSnjz6lWYJjPlZzEqCcog9j4jcShjEQzciU9mQLOB0FNzxTJpfh0gRYuncsnwGeJe2XFl2PzZh0gzU0huH1lzN3DxDCcOWBZcYCIcWpD9KensKHRrRlhebtoGnefPpJqP/s2TJirBHUyyKSr6y3gFd/v9P2BQO9emo2/7i9ojAX960P3H++L+nFThxyIjHmxoVuYzKsag2FlJiXOdN4KglIX28Ye5fYauBajnNQXGkzM9xEf8JrzlhNrurAxM/hoE66K8HDKCpDsjI6gSdvFSZQUK0ScoLfgO4qf3LVE+HFGMLeWe9tSmbs4YBfeaMms0d/zfJGQUj138DKw/58RMekYPNTP3bflijH3kw==
  template:
    metadata:
      name: auth-jwt-secret
      namespace: mini-ecommerce
    type: Opaque
